### ISSUE TITLE
using goreleaser to publish artifacts to github

### ISSUE THREAD

**Issue by ck1828** [caarlos0/goreleaser-action-v4-auto-snapshot-example#3]
Can you help me with this error
```
• publishing       
      • github/gitlab/gitea releases
         • creating or updating release repo=abc/def tag=v0.1.0
         • release updated           url=
   ⨯ release failed after 65.41s error=github/gitlab/gitea releases: failed to publish artifacts: POST https://github.com/repos/abc/def/releases: 403  []
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.184.0/x64/goreleaser' failed with exit code 1
```

This is my goreleaser.yaml
```
before:
  hooks:
    - go mod tidy

project_name: def
builds:
  - main: cmd/def/def.go
    ldflags:
      - -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
#      - arm64
release:
  github:
    owner: abc
    name: def

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ incpatch .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# .goreleaser.yaml
github_urls:
  api: https://github.com/
  
```
